<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <RollForward>major</RollForward>
    <TargetFrameworks>$(SupportedDotnetVersion);$(SupportedFrameworkVersion);$(LatestDotnetVersion);netcoreapp3.1</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LambdaTale.Execution\LambdaTale.Execution.csproj" />
  </ItemGroup>

    <Choose>
    <When
      Condition="$([MSBuild]::IsTargetFrameworkCompatible($(TargetFramework), $(SupportedDotnetVersion))) or $([MSBuild]::IsTargetFrameworkCompatible($(TargetFramework), $(SupportedFrameworkVersion)))">
      <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit.runner.visualstudio" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" VersionOverride="[17.13.0]" />
        <PackageReference Include="xunit.runner.visualstudio" VersionOverride="[2.4.5]" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
