<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NuspecFile>$(NUSPEC_FILE)</NuspecFile>
    <EnablePackageValidation>true</EnablePackageValidation>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="All" />
    <PackageReference Include="xunit.v3.extensibility.core" />
  </ItemGroup>

  <Target Name="InitializeNuspecProperties" AfterTargets="MinVer">

    <ItemGroup>
      <NuspecProperty Include="SupportedDotnetVersion=$(SupportedDotnetVersion)" />
      <NuspecProperty Include="SupportedFrameworkVersion=$(SupportedFrameworkVersion)" />
      <NuspecProperty Include="RepositoryCommit=$(SourceRevisionId)" />
      <NuspecProperty Include="RepositoryType=$(RepositoryType)" />
      <NuspecProperty Include="RepositoryUrl=$(PrivateRepositoryUrl)" />
      <NuspecProperty Include="Version=$(Version)" />
    </ItemGroup>

    <PropertyGroup>
      <NuspecProperties>@(NuspecProperty, ';')</NuspecProperties>
    </PropertyGroup>

  </Target>

</Project>
