<Project>

  <Import Project="..\Directory.Build.props"/>

  <PropertyGroup>
    <AnalysisMode>All</AnalysisMode>
    <TargetFrameworks>$(SupportedDotnetVersion);$(SupportedFrameworkVersion);netstandard2.0</TargetFrameworks>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
  </PropertyGroup>

  <!-- assembly signing -->
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)LambdaTale.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
<!--    <PackageReference Include="MinVer" PrivateAssets="All" />-->
  </ItemGroup>

</Project>
