<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageVersion Include="Bullseye" Version="6.0.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="4.14.0" />
    <PackageVersion Include="MinVer" Version="6.0.0" />
    <PackageVersion Include="SimpleExec" Version="12.0.0" />
    <PackageVersion Include="System.Linq.Async" Version="6.0.3" />
    <PackageVersion Include="xunit.analyzers" Version="1.24.0" />
    <PackageVersion Include="xunit.v3" Version="3.0.1" />
    <PackageVersion Include="xunit.v3.extensibility.core" Version="3.0.1" />
  </ItemGroup>
</Project>